config/routes.rb
Rails.application.routes.draw do

  resources :billings
  mount Notifications::Engine => "/notifications"
  resources :transactions

  resources :transactions do
    member do
      get 'details'
    end
  end
 
  class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 end
 get 'payment_history' => 'static_pages#payment_history'
 get 'subscribers' => 'static_pages#subscribers'  
  get 'feeds' => 'notifications#index'
  post 'web' => "retracts#web"
  get 'callback' => "transactions#callback"
  get 'upgrade' => "transactions#upgrade"  

  get '/' => 'static_pages#home'
  devise_for :users, :path => 'system-authentication'
  get '/system-authentication/sign_out' => 'sessions#destroy'
  root 'static_pages#home'
  get 'dashboard' => 'static_pages#home'
  get 'lawfirm-users-repository' => 'static_pages#lawfirmusers'
  get 'lawfirm-legalcases-repository' => 'static_pages#lawfirmcases'

  get 'lawfirm-legalcases-assign-cost' => 'static_pages#clawfirmcases'

   get 'lawfirm-legalcases-assign-attorney' => 'static_pages#assignattorney'
  
  get 'attorney-legalcases-repo' => 'static_pages#attorneycases'

   get 'attorney-legalcases-discussion' => 'static_pages#attorneycasesdis'
    get 'attorney-legalcases-tasks' => 'static_pages#attorneycasestask'

  get 'client-legalcases-repo' => 'static_pages#clientcases'
  get 'client-legalcases-discussion' => 'static_pages#clientcasesdis'

  get 'subcribers' =>'static_pages#subcribers'
  get 'lawfirm-attorneys-repository' => 'static_pages#attorneys'
get 'cases-completed-attorneys' => 'static_pages#cattorneys'

  get 'lawfirm-clients-repository' => 'static_pages#clients'
  get '7QXY84CQ3ZX9H21HQOVN24M5NF89L2WQQ4L3IUHW253C5JH60WA84622U9SRBYW8TMVE2B9Uacetrace-lawfirms-admins' => 'static_pages#admins'
  get 'legalcase-new-entry' => 'mycases#new'
  #get 'PW036GOYAVKRUI2S--24M5NF89L2WQQ4L3IU-HW253C5JH60WAnew-user-registration' => 'users#new'
  
get 'M0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-new-entry' => 'lawfirms#new'

 resources :users, :path => 'QI0V438P4SIPW036GOYAVKRUI2SOJT9QFPV8AGQ7YUNP3F8D8PWTH155QWQBBAMOCVGASQSMNKF-acetrace-membership-rep'
 #get 'users/user_id', to: 'users#show', as: 'acetracemembership'

resources :mycases, :path => 'QI0V438P4SIPW0-Legal-Case' do
  member do
    get 'meet'
    get 'billing'
	get 'casetask'
  get 'inview'
  get 'completed'
  patch 'assign_attorney'
  get 'new_assign'
  end
end
post 'create_admin' => 'admins#create' 
get 'PP9OCF35EPSYUSHXYDMPAJ27HA2BE70EO032OAAW5GFUDZ6PNRLZXGOWJE3L18YAWGVBXX2TPXY-create-admins-new'=> 'admins#new'

post 'create_users_admin' => 'users#create' 
patch 'update_users_admin' => 'users#update'
put 'update_users_admin' => 'users#update'

resources :users, as: 'users_admin', :path => 'Acetrace-users'
 
 resources :users_admin, :path => "acetracemembership"
 post 'create_sadmin' => 'sadmins#create' 
resources :sadmins
	resources :admins
resources :attorneys
resources :retracts
resources :clients
resources :lawfirms do
      member do
        get 'activate_lawfirm'
        get 'deactivate_lawfirm'
      end

    end
    

resources :adminassistants
resources :lawfirms, :path => 'L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo'
 

resources :mycasecomments, :path => 'Legal-case-discussion' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	
resources :tasks, :path => 'Legal-case-task' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	

resources :billings, :path => 'Legal-case-billing' do 
  member do
    get 'download_file'
    get 'approve_billing'
    #match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end 
  resources :mycases, :path => 'legal-case' do
     resources :mycasecomments
	   resources :tasks
  end	
  resources :tasks
  resources :mycases, :path => 'legal-case' do
     resources :tasks
  end 

  resources :mycases, :path => 'legal-case' do
     resources :billings
  end   
  resources :posts, :path => 'PFPM02FLORDO2WZF4QU47NORRUUP6WSU80K7K7VMRZKYP5JIDZAWLXP5KBNIMPV4E0QYWJSQUB5-acetracecms-forum-repo'
 resources :posts, :path => 'Acetrace-Forum-Post' do
     resources :comments
   
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :in_check
def in_check
  if current_user.admin? || current_user.adminassistant? || current_user.client? || current_user.attorney?
    if current_user.lawfirm
    if current_user.lawfirm.status == "inactive" ||  current_user.lawfirm.status == nil
         redirect_to new_transaction_path, notice: 'Your Lawfirm Subscription has Expire Contact your Lawfirm Admin!'
      end
      else
        redirect_to new_lawfirm_path, notice: 'Setup Your Lawfirm First'

end
  end

 end
def payment_history
  if current_user.admin? 
    if current_user.lawfirm.transactions
    @ress = current_user.lawfirm.transactions
  end
end

end


  def home
    if current_user.admin?
      if current_user.lawfirm == nil
       
        redirect_to new_lawfirm_path, notice: 'Admin Account was succesfully created. You have to set up your Lawfirm'
      end
      end
      @usersalls=User.all
      @user=current_user
      @mycases = Mycase.all
  @lawfirms = Lawfirm.all
  @admins = Admin.all
    lawfirmusers
   if current_user.admin? || current_user.attorney? || current_user.client?
    
    @user_cases ||= []
    if current_user.mycases.any?
       current_user.mycases.each do |u| 
        if u.client_id == current_user.id 
     @user_cases << u
      end
    end
  end
    end

    if current_user.admin?
         if current_user.lawfirm.transactions.any?
              rem = (current_user.lawfirm.transactions.last.expires_on - Date.today).to_s.split('/')
              @offset = rem[0].to_i

          end

    end


  if current_user.sadmin?
      paystackObj = Paystack.new(ENV['PUBLIC_KEY'], ENV['SECRET_KEY'])
      transactions = PaystackTransactions.new(paystackObj)
      @total = transactions.totals()
      @actives = Lawfirm.where(status: 1)
      @ats = Attorney.all
      @cls = Client.all
  end
end

    def subscribers
      @lawfirms = Lawfirm.where(status: 1).all.paginate(page: params[:page], per_page: 5)
    end

      def lawfirmusers
         if current_user.admin? || current_user.adminassistant? || current_user.client? || current_user.attorney?
     if current_user.lawfirm
          if current_user.attorney? || current_user.client?
            if current_user.mycases.any?

                  @aopen = current_user.mycases.where(status: 0).count
                  @ainview = current_user.mycases.where(status: 1).count
                  @acompleted = current_user.mycases.where(status: 2).count

                  @copen = current_user.mycases.where(status: 0).count
                  @cinview = current_user.mycases.where(status: 1).count
                  @ccompleted = current_user.mycases.where(status: 2).count

            else
                  @aopen = 0
                  @ainview = 0
                  @acompleted = 0

                   @copen = 0
                  @cinview = 0
                  @ccompleted = 0
            end
          end
    if current_user.lawfirm.mycases || current_user.lawfirm.clients || current_user.lawfirm.attorneys|| current_user.lawfirm.adminassistants
     @lawfirm_users ||= []
      @lawfirm_cases = current_user.lawfirm.mycases
     
      @lopen = current_user.lawfirm.mycases.where(status: 0)
      @linview = current_user.lawfirm.mycases.where(status: 1)
      @lcompleted = current_user.lawfirm.mycases.where(status: 2)
      

      
      
  
      @clients = current_user.lawfirm.clients
      
       @lawfirm_adminassistant = current_user.lawfirm.adminassistants
       @lawfirm_attorneys= current_user.lawfirm.attorneys
    
 @lawfirm_adminassistant.each do |u| 
     @lawfirm_users << u
    
    end

    @lawfirm_attorneys.each do |u| 
     @lawfirm_users << u
    
    end

    @clients.each do |u| 
     @lawfirm_users << u
    
    end

    @lawfirm_users << current_user

      end
    end
  end
  end
  def lawfirmcases
    home
  end

   def clawfirmcases
    home
  end

  def assignattorney
    home
  end



   def attorneycases
    home
  end

  def attorneycases
    home
  end

  def attorneycasesdis
    home
  end

   def clientcasesdis
    home
  end

     def clientcases
    home
  end



  def clients
    lawfirmusers  
end

  def admins
    home 
end



def attorneys
  lawfirmusers
  
 end


 def cattorneys
 lawfirmusers
 @com_attorneys ||= [] 
 @lawfirm_attorneys.each do |u|

  if u.mycases.any?
    u.mycases.each do |c|

      if c.status == "completed"
        @com_attorneys << u
      end and return
    end
  end
 end
 end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
# Returns the full title on a per-page basis.
	def full_title( page_title = '' )
		base_title = "Acetrace Case Management System"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end


	def lawfirmusercount
	 count = 0
	 if @lawfirm_users 
     @lawfirm_users.each do |user| 
		if user
			count +=1
		end
		end
	end
		return count
		
	end

	def attorneyscount
	 count = 0
	 if @lawfirm_attorneys 
    @lawfirm_attorneys.each do |user|
		if user
			count +=1
		end
		end
	end
		return count
		
	end

	def lawfirmscount
	 count = 0
	 if @lawfirms 
    @lawfirms.each do |lawfirm|
		if lawfirm
			count +=1
		end
		end
	end
		return count
		
	end


	def alluser
	 count = 0
	 if @usersalls 
    @usersalls.each do |lawfirm|
		if lawfirm
			count +=1
		end
		end
	end
		return count
		
	end

	def allcases
	 count = 0
	 if @mycases
    @mycases.each do |lawfirm|
		if lawfirm
			count +=1
		end
		end
	end
		return count
		
	end


   def attorneycases
   		count = 0
   		if current_user.mycases
   	current_user.mycases.each do |user|
		if user
			count +=1
		end
		end
	end
		return count


   end

def usercases
   		count = 0
   		if @user_cases 
   	@user_cases.each do |user|
		if user
			count +=1
		end
		end
	end
		return count


   end





	def clientscount
	 count = 0
	 if @clients 
    @clients.each do |user|
		if user
			count +=1
		end
		end
	end
		return count
		
	end


	def adminscount
	 count = 0
	 if @admins
    @admins.each do |user|
		if user
			count +=1
		end
		end
	end
		return count
		
	end


def lawfirmcasescount
	 count = 0
	 if @lawfirm_cases
    @lawfirm_cases.each do |user|
		if user
			count +=1
		end
		end
	end
		return count
		
	end




end

app/views/static_pages/admins.html.erb
<% provide( :title, "Lawfirm Admins") %>

<%if current_user.sadmin?%>


      <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Lawfirm Admins</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
         
  

</div>



    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />

                                    <table style="font-size:16px;" class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Admin</th>
                                                <th></th>
                                                <th>Lawfirm</th>
                                            </tr>
                                        </thead>
                                        <tbody>
            <% if @admins.any?%>
           <% @admins.each do |user| %>
            <div style="font-size:16px;">
<tr>
                                                <td style="width:50px;">
<%if user.avatars?%>
                                                <span class="prfil-img"><%= image_tag user.avatars_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                        <h5><%= user.full_name %></h5><small class="text-muted"><%= user.phone_number %></small><p><small> <%= user.email %></small></p></td>
                                                
                                                <td> <span>
    <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/Acetrace-users/<%=user.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
                                                </span>

        <span>  <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/Acetrace-users/<%=user.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

        </a></span>


        <span>

  <%= link_to users_admin_path(user.id), method: :delete, data: { confirm: 'Are you sure you really want to delete this post?' } do%><i onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" style="font-size:27px"class="fa fa-trash"></i><%end%>

        </span>


              </span></td>
              <%if user.lawfirm%>
                                                <td><%= user.lawfirm.name %></td>

                                                 <%else%>
   <td style="font-size:16px; color:red;"> This Admin did not create a Lawfirm</td>

                                                <%end%>
                                            </tr>
                                                       


<%end%>

                                        </tbody>
                                    </table>



           <%else%>
<h5>There are no admins yet!</h5>
<%end%>
</div>
<%= link_to 'Back to Dashboard', root_url, class:"btn btn-info" %>
<%= link_to "Back", :back, class:"btn btn-warning"%>



                                </div>
                            </div>
                        </div>
                    </div>




<%else%>

<h5>Your are not allowed to view this page</h5>

 <%end%>

app/views/static_pages/attorneycasesdis.html.erb
  <% provide( :title, "Attorney cases") %>

<h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;"> Attorney Cases Discussion</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 

</div>


    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />

<div class="col-md-12">
            <div class="card">
              


<div class="card-body card-body">


<% if current_user.mycases.any? %>

<div class="card-header">
                <h5 class="card-title"><strong>Legal Cases</strong></h5>

              </div>


<table class="table">
  <thead>
    <tr>
      <th>Caseno</th>
      <th>Client name</th>
      <th>Subject</th>
      <th>Arrival Date</th>
      <th>Due Date</th>
       <th>Lawfirm</th>
      <th>Show</th>
      <th>Update</th>
      
     
     
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.mycases.each do |mycase| %>
      <tr>
        <td><%= mycase.caseNo %></td>
        <td><%= mycase.client_name %></td>
        <td><%= mycase.subject %></td>
        
        <td><%= mycase.arrival_date %></td>
        <td><%= mycase.due_date %></td>
       
     <td><%= link_to current_user.lawfirm.name, lawfirm_path(current_user.lawfirm.id) %></td>       
        <td><%= link_to 'Show', mycase %></td>
        <td>
<%= link_to 'Discussions', meet_mycase_path(mycase) , class:'btn btn-info'%> 
</td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
<h5>There are no cases associated to you as an attorney yet!</h5>
<%end%>

</div>
</div>
</div>

app/views/static_pages/attorneycasestask.html.erb
  <% provide( :title, "Attorney cases") %>

<h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;"> Attorney Cases Tasks</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 

</div>


    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />

<div class="col-md-12">
            <div class="card">
              


<div class="card-body card-body">


<% if current_user.mycases.any? %>

<div class="card-header">
                <h5 class="card-title"><strong>Legal Cases</strong></h5>

              </div>


<table class="table">
  <thead>
    <tr>
      <th>Caseno</th>
      <th>Client name</th>
      <th>Subject</th>
      <th>Arrival Date</th>
      <th>Due Date</th>
       <th>Lawfirm</th>
      <th>Show</th>
      <th>Update</th>
      
     
     
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.mycases.each do |mycase| %>
      <tr>
        <td><%= mycase.caseNo %></td>
        <td><%= mycase.client_name %></td>
        <td><%= mycase.subject %></td>
        
        <td><%= mycase.arrival_date %></td>
        <td><%= mycase.due_date %></td>
       
     <td><%= link_to current_user.lawfirm.name, lawfirm_path(current_user.lawfirm.id) %></td>       
        <td><%= link_to 'Show', mycase %></td>
        <td><%= link_to 'See Task', casetask_mycase_path(mycase) , class:'btn btn-succes'%> </td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
<h5>There are no cases associated to you as an attorney yet!</h5>
<%end%>

</div>
</div>
</div>

app/views/static_pages/cattorneys.html.erb
<% provide( :title, "Lawfirm Attorneys") %>

<%if current_user.admin? || current_user.adminassistant?%>


     
      <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Lawfirm Attorneys that have completed their cases</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
         
  

</div>



    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details  </h3> </div> <div class="panel-body">
        <br />

                                    <table style="font-size:16px;" class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Info</th>
                                                <th colspan="2"></th>
                                               
                                            </tr>
                                        </thead>
                                        <tbody>
            <% if @com_attorneys.any?%>
           <% @com_attorneys.each do |user| %>
            <div style="font-size:16px;">
<tr>
                                                <td style="width:50px;">
<%if user.avatars?%>
                                                <span class="prfil-img"><%= image_tag user.avatars_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                        <h5><%= user.full_name %></h5><small class="text-muted"><%= user.phone_number %></small><p><small> <%= user.email %></small></p></td>
                                                
                                                <td> <span>
    <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/attorneys/<%=user.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
                                                </span>

        <span>  <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/attorneys/<%=user.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

      </td>
         
                                            
                                        

                                            </tr>
                                                       


<%end%>

                                        </tbody>
                                    </table>




           <%else%>
<h5>No Attorney has Completed his Case yet!</h5>
<%end%>


<%if current_user.admin?%>
<%= link_to 'Add New Attorney', new_attorney_path, class:"btn btn-success" %>
<%end%>
  <%= link_to 'Back to Dashboard', root_path, class:"btn btn-info" %> |

<%= link_to "Back", :back, class:"btn btn-warning"%> 

                                </div>
                            </div>
                        </div>
                    </div>




<%else%>

<h5>Your are not allowed to view this page</h5>

 <%end%>

app/views/static_pages/clientcasesdis.html.erb
 <% provide( :title, "Client cases") %>

<h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;"> Client Cases Discussion</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 

</div>


    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />


<div class="col-md-12">
            <div class="card">
              


<div class="card-body card-body">


<% if @user_cases.any? %>

<div class="card-header">
                <h5 class="card-title"><strong>Legal Cases</strong></h5>

              </div>


<table class="table">
  <thead>
    <tr>
      <th>Caseno</th>
      <th>Client name</th>
      <th>Subject</th>
      <th>Arrival Date</th>
      <th>Due Date</th>
       <th>Lawfirm</th>
      <th>Show</th>
     
      
     
     
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_cases.each do |mycase| %>
      <tr>
        <td><%= mycase.caseNo %></td>
        <td><%= mycase.client_name %></td>
        <td><%= mycase.subject %></td>
        
        <td><%= mycase.arrival_date %></td>
        <td><%= mycase.due_date %></td>
       
     <td><%= link_to current_user.lawfirm.name, lawfirm_path(current_user.lawfirm.id) %></td>
       
        <td><%= link_to 'Show', mycase %></td>
           <td>
<%= link_to 'Discussions', meet_mycase_path(mycase) , class:'btn btn-info'%> 
</td>
        
      
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
<h5>There are no cases associated to you as  client yet!</h5>
<%end%>

</div>
</div>
</div>

app/views/static_pages/clients.html.erb
<% provide( :title, "Lawfirm Clients") %>

<%if current_user.admin? || current_user.adminassistant?%>
       
      <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Lawfirm Clients</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
         
  
</div>
  
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />

                                    <table style="font-size:16px;" class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Info</th>
                                                <th></th>
                                                <th colspan="2">Entity</th>
                                            </tr>
                                        </thead>
                                        <tbody>
            <% if @clients.any?%>
           <% @clients.each do |user| %>
            <div style="font-size:16px;">
<tr>
                                                <td style="width:50px;">
<%if user.avatars?%>
                                                <span class="prfil-img"><%= image_tag user.avatars_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                        <h5><%= user.full_name %></h5><small class="text-muted"><%= user.phone_number %></small><p><small> <%= user.email %></small></p></td>
                                                
                                                <td> <span>
    <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/clients/<%=user.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
                                                </span>

        <span>  <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/clients/<%=user.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

        </a></span>


        <span>

  <%= link_to client_path(user.id), method: :delete, data: { confirm: 'Are you sure you really want to delete this post?' } do%><i onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" style="font-size:27px"class="fa fa-trash"></i><%end%>

        </span>


              </span></td>
              <td><%=user.entity%></td>
         
                                            </tr>
                                                       


<%end%>

                                        </tbody>
                                    </table>





           <%else%>
<h5>There are no Clients on this lawfirm yet!</h5>
<%end%>



<%= link_to 'Add New Client', new_client_path, class:"btn btn-success" %>
 <%= link_to 'Back to Dashboard', root_path, class:"btn btn-info" %> |

<%= link_to "Back", :back, class:"btn btn-warning"%> 

 

                                </div>
                            </div>
                        </div>
                    </div>




<%else%>

<h5>Your are not allowed to view this page</h5>

 <%end%>

app/views/static_pages/home.html.erb
<%if current_user.sadmin?%>
     <%= render 'superadmin' %>

<%elsif current_user.admin?%>

<%= render partial: 'admin' %>

<%elsif current_user.attorney?%>

<%= render partial: 'attorney' %>

<%elsif current_user.adminassistant?%>

<%= render partial: 'adminassistant' %>

<%elsif current_user.client?%>

<%= render partial: 'client' %>

<%end%>

app/views/static_pages/lawfirmusers.html.erb
<% provide( :title, "Lawfirm Users") %>

<%if current_user.admin? || current_user.adminassistant?%>


     
      <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Lawfirm Users</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
         
  

</div>



    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> Details</h3> </div> <div class="panel-body">
        <br />

                                    <table style="font-size:16px;" class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Info</th>
                                                <th></th>
                                               
                                            </tr>
                                        </thead>
                                        <tbody>
            <% if @lawfirm_users.any?%>
           <% @lawfirm_users.each do |user| %>
            <div style="font-size:16px;">
<tr>
                                                <td style="width:50px;">
<%if user.avatars?%>
                                                <span class="prfil-img"><%= image_tag user.avatars_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                        <h5><%= user.full_name %></h5><small class="text-muted"><%= user.phone_number %></small><p><small> <%= user.email %></small></p></td>
                                                
                                                <td> <span>
    <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/Acetrace-users/<%=user.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
                                                </span>

        <span>  <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/Acetrace-users/<%=user.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

        </a></span>


        <span>

  <%= link_to users_admin_path(user.id), method: :delete, data: { confirm: 'Are you sure you really want to delete this post?' } do%><i onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" style="font-size:27px"class="fa fa-trash"></i><%end%>

        </span>


              </span></td>
              <%if user.lawfirm%>
                                                <td><%= user.lawfirm.name %></td>

                                                 <%else%>
   <td style="font-size:16px; color:red;"> This Admin did not create a Lawfirm</td>

                                                <%end%>
                                            </tr>
                                                       


<%end%>

                                        </tbody>
                                    </table>

<%end%>
 <%= link_to 'Back to Dashboard', root_path, class:"btn btn-info" %> |

<%= link_to "Back", :back, class:"btn btn-warning"%> 


                                </div>
                            </div>
                        </div>
                    </div>




<%else%>

<h5>Your are not allowed to view this page</h5>

 <%end%>