config/routes.rb
Rails.application.routes.draw do

  resources :billings
  mount Notifications::Engine => "/notifications"
  resources :transactions

  resources :transactions do
    member do
      get 'details'
    end
  end
 
  class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 end
 get 'payment_history' => 'static_pages#payment_history'
 get 'subscribers' => 'static_pages#subscribers'  
  get 'feeds' => 'notifications#index'
  post 'web' => "retracts#web"
  get 'callback' => "transactions#callback"
  get 'upgrade' => "transactions#upgrade"  

  get '/' => 'static_pages#home'
  devise_for :users, :path => 'system-authentication'
  get '/system-authentication/sign_out' => 'sessions#destroy'
  root 'static_pages#home'
  get 'dashboard' => 'static_pages#home'
  get 'lawfirm-users-repository' => 'static_pages#lawfirmusers'
  get 'lawfirm-legalcases-repository' => 'static_pages#lawfirmcases'

  get 'lawfirm-legalcases-assign-cost' => 'static_pages#clawfirmcases'

   get 'lawfirm-legalcases-assign-attorney' => 'static_pages#assignattorney'
  
  get 'attorney-legalcases-repo' => 'static_pages#attorneycases'

   get 'attorney-legalcases-discussion' => 'static_pages#attorneycasesdis'
    get 'attorney-legalcases-tasks' => 'static_pages#attorneycasestask'

  get 'client-legalcases-repo' => 'static_pages#clientcases'
  get 'client-legalcases-discussion' => 'static_pages#clientcasesdis'

  get 'subcribers' =>'static_pages#subcribers'
  get 'lawfirm-attorneys-repository' => 'static_pages#attorneys'
get 'cases-completed-attorneys' => 'static_pages#cattorneys'

  get 'lawfirm-clients-repository' => 'static_pages#clients'
  get '7QXY84CQ3ZX9H21HQOVN24M5NF89L2WQQ4L3IUHW253C5JH60WA84622U9SRBYW8TMVE2B9Uacetrace-lawfirms-admins' => 'static_pages#admins'
  get 'legalcase-new-entry' => 'mycases#new'
  #get 'PW036GOYAVKRUI2S--24M5NF89L2WQQ4L3IU-HW253C5JH60WAnew-user-registration' => 'users#new'
  
get 'M0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-new-entry' => 'lawfirms#new'

 resources :users, :path => 'QI0V438P4SIPW036GOYAVKRUI2SOJT9QFPV8AGQ7YUNP3F8D8PWTH155QWQBBAMOCVGASQSMNKF-acetrace-membership-rep'
 #get 'users/user_id', to: 'users#show', as: 'acetracemembership'

resources :mycases, :path => 'QI0V438P4SIPW0-Legal-Case' do
  member do
    get 'meet'
    get 'billing'
	get 'casetask'
  get 'inview'
  get 'completed'
  patch 'assign_attorney'
  get 'new_assign'
  end
end
post 'create_admin' => 'admins#create' 
get 'PP9OCF35EPSYUSHXYDMPAJ27HA2BE70EO032OAAW5GFUDZ6PNRLZXGOWJE3L18YAWGVBXX2TPXY-create-admins-new'=> 'admins#new'

post 'create_users_admin' => 'users#create' 
patch 'update_users_admin' => 'users#update'
put 'update_users_admin' => 'users#update'

resources :users, as: 'users_admin', :path => 'Acetrace-users'
 
 resources :users_admin, :path => "acetracemembership"
 post 'create_sadmin' => 'sadmins#create' 
resources :sadmins
	resources :admins
resources :attorneys
resources :retracts
resources :clients
resources :lawfirms do
      member do
        get 'activate_lawfirm'
        get 'deactivate_lawfirm'
      end

    end
    

resources :adminassistants
resources :lawfirms, :path => 'L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo'
 

resources :mycasecomments, :path => 'Legal-case-discussion' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	
resources :tasks, :path => 'Legal-case-task' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	

resources :billings, :path => 'Legal-case-billing' do 
  member do
    get 'download_file'
    get 'approve_billing'
    #match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end 
  resources :mycases, :path => 'legal-case' do
     resources :mycasecomments
	   resources :tasks
  end	
  resources :tasks
  resources :mycases, :path => 'legal-case' do
     resources :tasks
  end 

  resources :mycases, :path => 'legal-case' do
     resources :billings
  end   
  resources :posts, :path => 'PFPM02FLORDO2WZF4QU47NORRUUP6WSU80K7K7VMRZKYP5JIDZAWLXP5KBNIMPV4E0QYWJSQUB5-acetracecms-forum-repo'
 resources :posts, :path => 'Acetrace-Forum-Post' do
     resources :comments
   
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lawfirm.rb
class Lawfirm < ApplicationRecord
  enum status: [:inactive, :active]
  has_many :transactions, dependent: :destroy
	belongs_to :admin, foreign_key: :admin_id
	has_many :clients, dependent: :destroy
  has_many :attorneys, dependent: :destroy
  has_many :adminassistants, dependent: :destroy
	has_many :mycases, dependent: :destroy
	mount_uploader :logos, LogosUploader
	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  #validates :info, presence: true, length: { maximum: 100 }
  validates :phone_number, presence: true, length: { maximum: 11 }
 
  validates :state, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :city, presence: true, length: { maximum: 50 }


  extend FriendlyId
  
    friendly_id :generate_caseNo, use: [:slugged, :history, :finders]
   



def generate_caseNo
        String.random(51, ['0'..'9','A'..'Z'] )

    end
    
    class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 

end


end

app/controllers/lawfirms_controller.rb
class LawfirmsController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout 'application', only: [:index, :show]
 #load_and_authorize_resource :lawfirm
  before_action :set_lawfirm, only: [:activate_lawfirm, :deactivate_lawfirm, :show, :edit, :update, :destroy]
before_action :in_check
def in_check
   if current_user.admin? || current_user.adminassistant? || current_user.client? || current_user.attorney?
      if current_user.lawfirm
    if current_user.lawfirm.status == "inactive" ||  current_user.lawfirm.status == nil
         redirect_to new_transaction_path, notice: 'Your Lawfirm Subscription has Expire Contact your Lawfirm Admin!'
      end
     
    end
end
  end
  # GET /lawfirms
  # GET /lawfirms.json
  def index
    @lawfirms = Lawfirm.all.paginate(page: params[:page], per_page: 5)
    
  end

  def show
  end

  def activate_lawfirm
    @lawfirm.update(status: 1)
   redirect_to @lawfirm, notice: 'Lawfirm was successfully activated.' 
  end

  def deactivate_lawfirm
    @lawfirm.update(status: 0)
    redirect_to @lawfirm, notice: 'Lawfirm was successfully deactivated.'
        
  end

  # GET /lawfirms/new
  def new
    if current_user.admin?
      @lawfirm = Lawfirm.new
    else
      redirect_to root_path, notice: 'Sorry, Only Lawfirm Admins Create Lawfirm'
    end
  end

  # GET /lawfirms/1/edit
  def edit
  end

  # POST /lawfirms
  # POST /lawfirms.json
  def create
    @lawfirm = Lawfirm.new(lawfirm_params)
    @lawfirm.admin_id= current_user.id
    #current_user.lawfirm = @lawfirm
    @lawfirm.status = 0
    @lawfirm.save
    respond_to do |format|
      if @lawfirm.save
        format.html { redirect_to @lawfirm, notice: 'Lawfirm was successfully created. Welcome to Acetracecms!' }
        format.json { render :show, status: :created, location: @lawfirm }
      else
        format.html { render :new }
        format.json { render json: @lawfirm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawfirms/1
  # PATCH/PUT /lawfirms/1.json
  def update
    respond_to do |format|
      if @lawfirm.update(lawfirm_params)
        format.html { redirect_to @lawfirm, notice: 'Lawfirm was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawfirm }
      else
        format.html { render :edit }
        format.json { render json: @lawfirm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawfirms/1
  # DELETE /lawfirms/1.json
  def destroy
    @lawfirm.destroy
    respond_to do |format|
      format.html { redirect_to lawfirms_url, notice: 'Lawfirm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawfirm
      @lawfirm = Lawfirm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawfirm_params
      params.require(:lawfirm).permit(:status, :interval, :name,:logos,:remove_logos, :logos_cache, :type_of_organization, :address, :email, :phone_number, :state, :city)
    end
	 #resourcify
end

app/helpers/lawfirms_helper.rb
module LawfirmsHelper
end

app/views/lawfirms/_form.html.erb
<%= form_with(model: lawfirm, local: true, html: { multipart: true }) do |form| %>
  <% if lawfirm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lawfirm.errors.count, "error") %> prohibited this lawfirm from being saved:</h2>

      <ul>
      <% lawfirm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-12 panel-grids">
</div>
 
            <div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> New Lawfirm </h3> </div> <div class="panel-body">


              <form> 

                <div class="row">
  <div class="col-md-6">
   <div class="form-group">
    <%= form.label :name, "Name of Lawfirm" %>
    <%= form.text_field :name, id: :lawfirm_name,  type:"text",required:"required", class:"form-control" %>
  </div></div>

  <div class="col-md-6">
 <div class="form-group">
  
 
  <%= form.label :logo, "Lawfirm Logo" %>
    
	<%= form.file_field :logos, autofocus: true, class:"form-control" %>
  

  </div>
   
  </div>
  
  <div class="col-md-6">
  <div class="form-group">
    <%= form.label :info, "About Lawfirm" %>
    <%= form.text_area :info, id: :lawfirm_info, type:"text", required:"required",style:"height:250px;", class:"form-control" %>
  </div></div>

      


 <div class="col-md-6">
      <div class="form-group">
  <h2><i class="fa fa-sitemap"></i>Type of Organization</h2>
   
      <h2><%= f.radio_button :type_of_organization, "Lawfirm", required:"required",  class:"form-control has-feedback-left" %> Lawfirm</h2>
    <h2><%= f.radio_button :type_of_organization, "Legal Chamber", required:"required",  class:"form-control has-feedback-left" %>Legal Chamber</h2>

    <h2><%= f.radio_button :type_of_organization, "Legal Institution", required:"required",  class:"form-control has-feedback-left" %>Legal Institution</h2>
 
          </div>
          </div>

<div class="col-md-6">
  <div class="form-group">
    <%= form.label :email, "Lawfirm Email" %>
    <%= form.text_field :email, id: :lawfirm_email, required:"required", class:"form-control" %>
  </div></div>
<div class="col-md-6">
  <div class="form-group">
    <%= form.label :phone_number, "Lawfirm Telephone" %>
    <%= form.number_field :phone_number, id: :lawfirm_phone_number, type:"number",required:"required", class:"form-control"%>
  </div></div>
  <div class="col-md-6">
  <div class="form-group">
    <%= form.label :address, "Lawfirm Address" %>
    <%= form.text_field :address, id: :lawfirm_address, type:"text", required:"required", class:"form-control"%>
  </div></div>
<div class="col-md-6">
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, id: :lawfirm_city, type:"text", required:"required", class:"form-control"%>
  </div></div>
 
 
<div class="col-md-6">
 <div class="form-group">
    <%= form.label :state %>
   <%= form.select :state, ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta", "Ebonyi","Edo","Ekiti","Enugu","FCT","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nassarawa","Niger","Ogun","Ondo","Osun","Oyo State","Plateau","River State","Sokoto","Taraba","Yobe","Zamfara"], prompt: "Select...",class:"custom-select form-control pull-right", required:"required"%>
         
  </div></div>
   

   <div class="action"> <%= form.submit "Create Lawfirm" , class: "btn btn-success" %>   
</form>
  </div></div>
</div>
</div>
</div>
</div>
<% end %>

app/views/lawfirms/edit.html.erb
<%if current_user.admin? || current_user.sadmin?%>
   <div class="login-page ">
  

<h2 class="title1"><img src="../assets/img/actionaid-logo.png" style="float:left;"/>Edit Lawfirm Form</h2>
<div class="sign-up-row widget-shadow">
<%= form_with(model: @lawfirm, local: true, html: { multipart: true }) do |form| %>
  <% if @lawfirm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lawfirm.errors.count, "error") %> prohibited this lawfirm from being saved:</h2>

      <ul>
      <% @lawfirm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form>

<div class="sign-u">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lawfirm_name, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
  <label>My Logo</label>
  info
    <%= image_tag(@lawfirm.logos_url)%>
       <%= form.file_field :logos %>
	    <label>
        <%= form.check_box :remove_logos %>
         Remove Logo
        </label>
	
    <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :type_of_organization %>
    <%= form.text_field :type_of_organization, id: :lawfirm_type_of_organization, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :address %>
    <%= form.text_field :address, id: :lawfirm_address, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :email %>
    <%= form.text_field :email, id: :lawfirm_email, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number, id: :lawfirm_phone_number, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :state %>
    <%= form.text_field :state, id: :lawfirm_state, class: 'form-control' %>
   <div class="clearfix"> </div>
          </div>


   <div class="sign-u">
    <%= form.label :city %>
    <%= form.text_field :city, id: :lawfirm_city , class: 'form-control'%>
  <div class="clearfix"> </div>
          </div>


          <div class="sub_home">
    <%= form.submit "Update" , class: "btn btn-primary" %>
 <div class="clearfix"> </div>
          </div>
 </form>
<% end %>


<%= link_to 'Show', @lawfirm, class:"btn btn-info" %> |
 <%= link_to "Back", :back, class:"btn btn-warning"%>
<br>
<br>
<br>
   
            </div>
          </div>

       
      </div>
    </div>



<%else%>

<h5>Your are not authorized  to view this page</h5>

 <%end%>

app/views/lawfirms/index.html.erb
<% provide( :title, "Lawfirms Repo") %>

<%if current_user.sadmin?%>


    
 <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Lawfirms</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
    
</div>
    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title">registered lawfirms</h3> </div> <div class="panel-body">              
                            </div>

                                    <table class="table table-hover earning-box">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Name</th>
                                               
                                                <th>Email</th>
                                                <th>Status</th>
                                                <th colspan="2"></th>
                                            </tr>
                                        </thead>
     <div style="font-size:16px;">                                    <tbody>

 <% @lawfirms.each do |lawfirm| %>
            <%unless lawfirm.name == "Acetracecms"%>
            

                                            <tr>
                                                <td style="width:50px;">
<%if lawfirm.logos?%>
                                                <span class="round"><%= image_tag lawfirm.logos_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                                                    <h6><%= lawfirm.name %></h6><small class="text-muted"><%= lawfirm.phone_number %></small></td>
                                               
                                                <td><%= lawfirm.email %></td>
                                                <td><%= lawfirm.status %></td>

                                                 <td> 



         <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo/<%=lawfirm.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
     

        

        <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo/<%=lawfirm.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

<%= link_to lawfirm, method: :delete, data: { confirm: 'Are you sure you really want to delete this post?' } do%><i onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" style="font-size:27px"class="fa fa-trash"></i><%end%>
</td>
                                            </tr>
                                                       <%end%>


<%end%>

                                        </tbody>
                                    </table>
                                    <%= will_paginate @lawfirms, :renderer => BootstrapPagination::Rails %>
                                </div>
                            </div>
                        </div>
                    </div>

</div>
 
</div>
</div>


<%else%>

<h5>Your are not authorized  to view this page</h5>

 <%end%>

<%= link_to 'Dashboard', root_url, class:"btn btn-info" %>
<%= link_to "Back", :back, class:"btn btn-warning"%>





     

app/views/lawfirms/new.html.erb
<% provide( :title, "Setup Lawfirm") %>

<%if current_user.admin? || current_user.sadmin?%>

 <div class="row">
   <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                               
  

<h2 class="title1"><img src="../assets/img/actionaid-logo.png" style="float:left;"/>New Lawfirm Form</h2>

<%= render 'form', lawfirm: @lawfirm %>

</div>
<%else%>

<h5>Your are not authorized  to view this page</h5>

 <%end%>



   

app/views/lawfirms/show.html.erb
<% provide( :title, @lawfirm.name) %>

  <h1 class="title1">Profile Info</h1>
<div class="col-md-12 panel-grids">
</div>
 
            <div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title">  <%= @lawfirm.name.capitalize %></h3> </div> <div class="panel-body">

<div class="col-md-4 widget widget1 panel-grids">
          

 <div class="row">
  
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
       
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
           <div class="profile-userpic">
           <%if @lawfirm.logos?%>
       <%= image_tag @lawfirm.logos_url, class:"img-circle" %>


        <%else%>

        <img class:"img-circle" src="../assets/fallback/logo.png" />
        <%end%>


        </div>
             <%= @lawfirm.name %>
          </div>
          <div class="profile-usertitle-job">
            <%= @lawfirm.type_of_organization %>
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li class="active">
              <a href="#">
              <i class="fa fa-home"></i>
               <%= @lawfirm.address %> </a>
            </li>
            
            <li>
              <a href="#" target="_blank">
              <i class="fa fa-ok"></i>
              <%= @lawfirm.email %> </a>
            </li>
            <li>
              <a href="#">
              <i class="fa fa-flag"></i>
              Enquiries </a>
            </li>
          </ul>
        </div>
        <!-- END MENU -->
      </div>

    </div>
   
    </div>
    <div class="col-md-6 widget widget1">
            <div class="r3_counter_box">
            <div class="profile-content">
         <table class="table">

        <tbody>

        <tr>
 <div style="font-size:16px;">
                      <tr>
                        <td>Company Name:</td>
                        <td><%= @lawfirm.name %></td>
                      </tr>
                      
                      <tr>
                       <tr>
                        <td>Subscription Status:</td>
                        <td><%= @lawfirm.status %></td>
                      </tr>
                      <tr>
                        <td>Type of Organization:</td>
                        <td><%= @lawfirm.type_of_organization %></td>
                      </tr>
                      <tr>
                        <td>Office Address:</td>
                        <td><%= @lawfirm.address %></td>
                      </tr>
                   
                         <tr>
                             <tr>
                        <td>Telephone:</td>
                        <td> <%= @lawfirm.phone_number %></td>
                      </tr>
                        <tr>
                        <td>State:</td>
                        <td><%= @lawfirm.state %></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><a href="mailto:info@support.com">info@support.com</a></td>
                      </tr>
                        <td>City:</td>
                        <td><%= @lawfirm.city %></td>
                           
                      </tr>
                      </tr>
                        <td>Status:</td>
                        <td><%= @lawfirm.status %></td>
                           
                      </tr>
                     
                    </tbody>
                  </table>
                  </div>
                  </div>
</div>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<%if current_user.sadmin?%>

<% if @lawfirm.status == "inactive"%>
<%= link_to 'Activate Lawfirm', activate_lawfirm_lawfirm_path(@lawfirm.id), class:'btn btn-success' %> 
<%else%>

<%= link_to 'Deactivate Lawfirm', deactivate_lawfirm_lawfirm_path(@lawfirm.id), class:'btn btn-danger' %> 
<%end%>

<%end%>


<%= link_to 'Edit', edit_lawfirm_path(@lawfirm) %> |

  <%= link_to 'Back to Dashboard', root_path, class:"btn btn-info" %> |

<%= link_to "Back", :back, class:"btn btn-warning"%> 

            </div>
    </div>
  </div>
</div>
</div>







 