config/routes.rb
Rails.application.routes.draw do

  resources :billings
  mount Notifications::Engine => "/notifications"
  resources :transactions

  resources :transactions do
    member do
      get 'details'
    end
  end
 
  class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 end
 get 'payment_history' => 'static_pages#payment_history'
 get 'subscribers' => 'static_pages#subscribers'  
  get 'feeds' => 'notifications#index'
  post 'web' => "retracts#web"
  get 'callback' => "transactions#callback"
  get 'upgrade' => "transactions#upgrade"  

  get '/' => 'static_pages#home'
  devise_for :users, :path => 'system-authentication'
  get '/system-authentication/sign_out' => 'sessions#destroy'
  root 'static_pages#home'
  get 'dashboard' => 'static_pages#home'
  get 'lawfirm-users-repository' => 'static_pages#lawfirmusers'
  get 'lawfirm-legalcases-repository' => 'static_pages#lawfirmcases'

  get 'lawfirm-legalcases-assign-cost' => 'static_pages#clawfirmcases'

   get 'lawfirm-legalcases-assign-attorney' => 'static_pages#assignattorney'
  
  get 'attorney-legalcases-repo' => 'static_pages#attorneycases'

   get 'attorney-legalcases-discussion' => 'static_pages#attorneycasesdis'
    get 'attorney-legalcases-tasks' => 'static_pages#attorneycasestask'

  get 'client-legalcases-repo' => 'static_pages#clientcases'
  get 'client-legalcases-discussion' => 'static_pages#clientcasesdis'

  get 'subcribers' =>'static_pages#subcribers'
  get 'lawfirm-attorneys-repository' => 'static_pages#attorneys'
get 'cases-completed-attorneys' => 'static_pages#cattorneys'

  get 'lawfirm-clients-repository' => 'static_pages#clients'
  get '7QXY84CQ3ZX9H21HQOVN24M5NF89L2WQQ4L3IUHW253C5JH60WA84622U9SRBYW8TMVE2B9Uacetrace-lawfirms-admins' => 'static_pages#admins'
  get 'legalcase-new-entry' => 'mycases#new'
  #get 'PW036GOYAVKRUI2S--24M5NF89L2WQQ4L3IU-HW253C5JH60WAnew-user-registration' => 'users#new'
  
get 'M0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-new-entry' => 'lawfirms#new'

 resources :users, :path => 'QI0V438P4SIPW036GOYAVKRUI2SOJT9QFPV8AGQ7YUNP3F8D8PWTH155QWQBBAMOCVGASQSMNKF-acetrace-membership-rep'
 #get 'users/user_id', to: 'users#show', as: 'acetracemembership'

resources :mycases, :path => 'QI0V438P4SIPW0-Legal-Case' do
  member do
    get 'meet'
    get 'billing'
	get 'casetask'
  get 'inview'
  get 'completed'
  patch 'assign_attorney'
  get 'new_assign'
  end
end
post 'create_admin' => 'admins#create' 
get 'PP9OCF35EPSYUSHXYDMPAJ27HA2BE70EO032OAAW5GFUDZ6PNRLZXGOWJE3L18YAWGVBXX2TPXY-create-admins-new'=> 'admins#new'

post 'create_users_admin' => 'users#create' 
patch 'update_users_admin' => 'users#update'
put 'update_users_admin' => 'users#update'

resources :users, as: 'users_admin', :path => 'Acetrace-users'
 
 resources :users_admin, :path => "acetracemembership"
 post 'create_sadmin' => 'sadmins#create' 
resources :sadmins
	resources :admins
resources :attorneys
resources :retracts
resources :clients
resources :lawfirms do
      member do
        get 'activate_lawfirm'
        get 'deactivate_lawfirm'
      end

    end
    

resources :adminassistants
resources :lawfirms, :path => 'L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo'
 

resources :mycasecomments, :path => 'Legal-case-discussion' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	
resources :tasks, :path => 'Legal-case-task' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	

resources :billings, :path => 'Legal-case-billing' do 
  member do
    get 'download_file'
    get 'approve_billing'
    #match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end 
  resources :mycases, :path => 'legal-case' do
     resources :mycasecomments
	   resources :tasks
  end	
  resources :tasks
  resources :mycases, :path => 'legal-case' do
     resources :tasks
  end 

  resources :mycases, :path => 'legal-case' do
     resources :billings
  end   
  resources :posts, :path => 'PFPM02FLORDO2WZF4QU47NORRUUP6WSU80K7K7VMRZKYP5JIDZAWLXP5KBNIMPV4E0QYWJSQUB5-acetracecms-forum-repo'
 resources :posts, :path => 'Acetrace-Forum-Post' do
     resources :comments
   
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sadmin.rb
class Sadmin < User

end

app/controllers/sadmins_controller.rb
class SadminsController < ApplicationController
  skip_before_action :verify_authenticity_token
#skip_before_action :authenticate_user!

	def new
   @user = Sadmin.new
 	#@lawfirm = Lawfirm.find(params[:lawfirm_id])
    #@user = @lawfirm.users.build(user_params)
  end

  def index
    @users = Sadmin.all
 
  end
  
  def show
    @user = Sadmin.find(params[:id])
  end
   
  def create

    @user=Sadmin.create(user_params)

    @user.save
	  respond_to do |format|
      if @user.save
        format.html { redirect_to  @user, notice: 'Successfully added Superadmin.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        
      end
    end
	  
	  
  end

   private
    # Use callbacks to share common setup or constraints between actions.
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:sadmin).permit!
    end
  

end

app/views/sadmins/index.html.erb
<% provide( :title, "S.Admins Repo") %>

<%if current_user.sadmin?%>

    
 <h2 class="title1" style="background-color:#edeff2;height: 50px; font-size:40px; color:orange;">Super Admins</h2>
          <div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
    
</div>
    
<div class="col-md-12 panel-grids">
<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title">registered system admins</h3> </div> <div class="panel-body">              
                            </div>
                                    <table class="table table-hover earning-box">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Name</th>
                                                <th></th>
                                                <th>Email</th>
                                            </tr>
                                        </thead>
                                        <tbody>
           <% @users.each do |user| %>
            
<tr>
                                                <td style="width:50px;">
<%if user.avatars?%>
                                                <span class="round"><%= image_tag user.avatars_url, style:"width:50px;" %>
<%end%>
                                            </span></td>
                                                <td>
                                                    <h6><%= user.full_name %></h6><small class="text-muted"><%= user.phone_number %></small></td>
                                                <td> 

         <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/sadmins/<%=user.id%>">
        <i style="font-size:27px"class="fa fa-eye"></i>

        </a>
     

        

        <a onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" href="/sadmins/<%=user.id%>/edit">
        <i style="font-size:27px"class="fa fa-edit"></i>

<%= link_to user, method: :delete, data: { confirm: 'Are you sure you really want to delete this post?' } do%><i onMouseOver="this.style.color='orange'"
   onMouseOut="this.style.color='#73879C'" style="font-size:27px"class="fa fa-trash"></i><%end%>

</td>
                                                <td><%= user.email %></td>
                                            </tr>
                                                       


<%end%>

                                        </tbody>
                                    </table>




                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                    </div>
                    

<%else%>

<h5>Your are not authorized  to view this page</h5>

 <%end%>

<%= link_to 'Dashboard', root_url, class:"btn btn-info" %>
<%= link_to "Back", :back, class:"btn btn-warning"%>

app/views/sadmins/new.html.erb
<% provide( :title, "New S.Admins") %>

<%if current_user.sadmin?%>



<div class="col-md-12 panel-grids">
</div>
 
            <div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title"> New Super Admin </h3> </div> <div class="panel-body">


           

                <div class="row">

<div >
<%= form_for(@user,  url: create_sadmin_url(@user), html: { multipart: true }) do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>
   <form> 
      <div class="col-md-6">
      <div class="form-group">
      <%= f.label :first_name %>
    

    <%= f.text_field :first_name, autofocus: true, type:"text", required:"required", class:"form-control"%>

      </div></div>
      <br>
<div class="col-md-6">
<div class="form-group">
    <%= f.label :last_name %>
	
    <%= f.text_field :last_name,  autofocus: true, type:"text", required:"required", class:"form-control" %>
 
   </div></div>

 

<div class="col-md-6">
 <div class="form-group">
  <%= f.label :avatars, "Profile Pic" %>
 
   <%= image_tag(@user.avatars_url) if @user.avatars? %>
    <%= f.file_field :avatars, autofocus: true, class:"form-control" %>
	 <%= f.hidden_field :avatars_cache %>
	
</div>
   </div> 

   <div class="col-md-6">
<div class="form-group">
    <%= f.label :birthday%>
	
    <%= f.date_field :birthday, autofocus: true, class:"form-control"  %>
 
 </div></div>
 <div class="col-md-6">
 <div class="form-group">
    <%= f.label :address %>

    <%= f.text_field :address, autofocus: true, type:"text", required:"required", class:"form-control"  %>
 
   </div></div>
  <div class="col-md-6">
 <div class="form-group">
    <%= f.label :email %><br />
	
    <%= f.email_field :email, autofocus: true, type:"email", required:"required", class:"form-control" %>
 
 </div></div>
 <div class="col-md-6">
  <div class="form-group">
    <%= f.label :password %>
	
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
	
    <%= f.password_field :password, autocomplete: "off", type:"password", required:"required", class:"form-control" %>
 
 </div></div>
 <div class="col-md-6">
 <div class="form-group">
    <%= f.label :password_confirmation%><br />
	
    <%= f.password_field :password_confirmation, autocomplete: "off", type:"password", required:"required", class:"form-control"%>
 
 </div></div>
 <div class="col-md-6">
<div class="form-group">
    <%= f.label :phone_number %>
	
    <%= f.number_field :phone_number, type:"number", required:"required", class:"form-control" %>
  
 </div>
 <div class="form-group">
    <%= f.label :state%>
	
    <%= f.text_field :state, type:"text", required:"required", class:"form-control"%>
  
 </div></div>
 <div class="col-md-6">
<div class="form-group">
    <%= f.label :city%>
	
    <%= f.text_field :city, type:"text", required:"required", class:"form-control"%>

  </div> </div>


<div class="action">
                     
    <%= f.submit "Create Superadmin account" , class: "btn btn-info" %>
 <%= link_to "Cancel", :back, class:"btn btn-warning"%>
  </div></form>
<% end %>
<br/>
<br/>
 

 
</div>
</div>
</div>

<%else%>

<h5>Your are not authorized  to view this page</h5>

 <%end%>

<%= link_to 'Dashboard', root_url, class:"btn btn-info" %>
<%= link_to "Back", :back, class:"btn btn-warning"%>




</div>
</div>

app/views/sadmins/show.html.erb
<% provide( :title, @user.full_name) %>

<%if current_user.sadmin?%>
     <h1 class="title1">Profile Info</h1>
<div class="col-md-12 panel-grids">
</div>
 
            <div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title">  <%= @user.first_name.capitalize if @user.first_name %> <%= @user.last_name.capitalize if @user.last_name %></h3> </div> <div class="panel-body">

<div class="col-md-4 widget widget1 panel-grids">
          

 <div class="row">
  
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
          <div class="profile-userpic">
       <%if @user.avatars?%>
        <%= image_tag(@user.avatars_url) %>

        <%else%>

        <img src="../assets/fallback/default.png"/>
        <%end%>

        </div>
           <%= @user.first_name.capitalize if @user.first_name %> <%= @user.last_name.capitalize if @user.last_name %>
          </div>
          <div class="profile-usertitle-job">
           <%= @user.type %>

          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">
          <center><button type="button" class="btn btn-success btn-sm">Acetracecms</button></center>
          
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li class="active">
             <%if current_user == @user%>
              <%= link_to edit_user_registration_path(@user) do%> <i class="fa fa-user"></i>Account Settings<%end%>
              <%end%>
            </li>
            

            </ul>
        </div>
        <!-- END MENU -->
      </div>

    </div>
   
    </div>
    <div class="col-md-6 widget widget1">
            <div class="r3_counter_box">
            <div class="profile-content">
         <table class="table">

        <tbody>


<tr>

<%if @user.phone_number%>
<td>
  <strong>Phone:</strong>
  <%= @user.phone_number %>
</td></tr>
<tr>
<%end%>
<%if @user.email%>
<td>
  <strong>Email:</strong>
  <%= @user.email%>
</td></tr>
<tr>
<%end%>
<%if @user.address%>
<td>
  <strong>Address:</strong>
  <%= @user.address %>
</td></tr>
<tr>
<%end%>

<%if @user.birthday%>
<td>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</td></tr>
<tr>
<%end%>

<%if @user.city%>
<td>
  <strong>Location:</strong>
  <%= @user.city %>
</td></tr>
<tr>
<%end%>
<%if @user.state%>
<td>
  <strong>State:</strong>
  <%= @user.state%>
</td></tr>
<tr>
<%end%>



         
          <tr>
          <td>
          <%= link_to 'Edit', edit_sadmin_path(@user), class:"btn btn-success" %> 
          </td>
          </tr>


          <%else%>

<h5 style="color:red;">Your are not authorized  to view this page</h5>

 <%end%>

           <tr>
          <td>
          <%= link_to 'Back to Dashboard', root_url, class:"btn btn-info" %>
          </td>
          </tr>
           <tr>
          <td>
          <%= link_to "Back", :back, class:"btn btn-warning"%> 
          </td>
          </tr>
          </tbody>
          </table>


 

<br/>

</div>

</div>

</div>



<br>
<br>




  