config/routes.rb
Rails.application.routes.draw do

  resources :billings
  mount Notifications::Engine => "/notifications"
  resources :transactions

  resources :transactions do
    member do
      get 'details'
    end
  end
 
  class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 end
 get 'payment_history' => 'static_pages#payment_history'
 get 'subscribers' => 'static_pages#subscribers'  
  get 'feeds' => 'notifications#index'
  post 'web' => "retracts#web"
  get 'callback' => "transactions#callback"
  get 'upgrade' => "transactions#upgrade"  

  get '/' => 'static_pages#home'
  devise_for :users, :path => 'system-authentication'
  get '/system-authentication/sign_out' => 'sessions#destroy'
  root 'static_pages#home'
  get 'dashboard' => 'static_pages#home'
  get 'lawfirm-users-repository' => 'static_pages#lawfirmusers'
  get 'lawfirm-legalcases-repository' => 'static_pages#lawfirmcases'

  get 'lawfirm-legalcases-assign-cost' => 'static_pages#clawfirmcases'

   get 'lawfirm-legalcases-assign-attorney' => 'static_pages#assignattorney'
  
  get 'attorney-legalcases-repo' => 'static_pages#attorneycases'

   get 'attorney-legalcases-discussion' => 'static_pages#attorneycasesdis'
    get 'attorney-legalcases-tasks' => 'static_pages#attorneycasestask'

  get 'client-legalcases-repo' => 'static_pages#clientcases'
  get 'client-legalcases-discussion' => 'static_pages#clientcasesdis'

  get 'subcribers' =>'static_pages#subcribers'
  get 'lawfirm-attorneys-repository' => 'static_pages#attorneys'
get 'cases-completed-attorneys' => 'static_pages#cattorneys'

  get 'lawfirm-clients-repository' => 'static_pages#clients'
  get '7QXY84CQ3ZX9H21HQOVN24M5NF89L2WQQ4L3IUHW253C5JH60WA84622U9SRBYW8TMVE2B9Uacetrace-lawfirms-admins' => 'static_pages#admins'
  get 'legalcase-new-entry' => 'mycases#new'
  #get 'PW036GOYAVKRUI2S--24M5NF89L2WQQ4L3IU-HW253C5JH60WAnew-user-registration' => 'users#new'
  
get 'M0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-new-entry' => 'lawfirms#new'

 resources :users, :path => 'QI0V438P4SIPW036GOYAVKRUI2SOJT9QFPV8AGQ7YUNP3F8D8PWTH155QWQBBAMOCVGASQSMNKF-acetrace-membership-rep'
 #get 'users/user_id', to: 'users#show', as: 'acetracemembership'

resources :mycases, :path => 'QI0V438P4SIPW0-Legal-Case' do
  member do
    get 'meet'
    get 'billing'
	get 'casetask'
  get 'inview'
  get 'completed'
  patch 'assign_attorney'
  get 'new_assign'
  end
end
post 'create_admin' => 'admins#create' 
get 'PP9OCF35EPSYUSHXYDMPAJ27HA2BE70EO032OAAW5GFUDZ6PNRLZXGOWJE3L18YAWGVBXX2TPXY-create-admins-new'=> 'admins#new'

post 'create_users_admin' => 'users#create' 
patch 'update_users_admin' => 'users#update'
put 'update_users_admin' => 'users#update'

resources :users, as: 'users_admin', :path => 'Acetrace-users'
 
 resources :users_admin, :path => "acetracemembership"
 post 'create_sadmin' => 'sadmins#create' 
resources :sadmins
	resources :admins
resources :attorneys
resources :retracts
resources :clients
resources :lawfirms do
      member do
        get 'activate_lawfirm'
        get 'deactivate_lawfirm'
      end

    end
    

resources :adminassistants
resources :lawfirms, :path => 'L3D7ZLU9SEMWM0R7F8O906ILVU5WY91WV4MUJJKSTM774ONCMBTNVTMNJJHSQKH80OCASGF3F0S-acetrace-lawfirms-repo'
 

resources :mycasecomments, :path => 'Legal-case-discussion' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	
resources :tasks, :path => 'Legal-case-task' do 
	member do
		get 'download_file'
		#match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end	

resources :billings, :path => 'Legal-case-billing' do 
  member do
    get 'download_file'
    get 'approve_billing'
    #match 'mycasecomments/download_file/:id', => 'mycasecomments#download_file' :as => :attachment 
  end
end 
  resources :mycases, :path => 'legal-case' do
     resources :mycasecomments
	   resources :tasks
  end	
  resources :tasks
  resources :mycases, :path => 'legal-case' do
     resources :tasks
  end 

  resources :mycases, :path => 'legal-case' do
     resources :billings
  end   
  resources :posts, :path => 'PFPM02FLORDO2WZF4QU47NORRUUP6WSU80K7K7VMRZKYP5JIDZAWLXP5KBNIMPV4E0QYWJSQUB5-acetracecms-forum-repo'
 resources :posts, :path => 'Acetrace-Forum-Post' do
     resources :comments
   
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mycasecomment.rb
class Mycasecomment < ApplicationRecord
  belongs_to :mycasecommenter, polymorphic: true
  belongs_to :mycase
  #delegate :first_name, to: :user, prefix: true, allow_nil: true
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   #validates :content, presence: true # Make sure the owner's name is present.
     #serialize :attachment, JSON # If you use SQLite, add this line.
   #has_attached_file :attachment,
   #:path => ':rails_root/public/uploads/attachment/:id/:basename.:extension'
    # attr_protected :attachment_file_name, :attachment_content_type, :attachment_file_size

   
   def filename
    File.basename(path)
  end


     extend FriendlyId
  
    friendly_id :generate_caseNo, use: [:slugged, :history, :finders]
   



def generate_caseNo
        String.random(25, ['0'..'9','A'..'Z'] )

    end
    
    
    class String
    def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
    chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
    Array.new(len){ chars.sample }.join
  end
 

end



end

app/controllers/mycasecomments_controller.rb
class MycasecommentsController < ApplicationController
  before_action :set_mycasecomment, only: [:show, :edit, :update, :destroy]
before_action :in_check
def in_check
   if current_user.admin? || current_user.adminassistant? || current_user.client? || current_user.attorney?
    if current_user.lawfirm
    if current_user.lawfirm.status == "inactive" ||  current_user.lawfirm.status == nil
         redirect_to new_transaction_path, notice: 'Your Lawfirm Subscription has Expire Contact your Lawfirm Admin!'
      end
      else
        redirect_to new_lawfirm_path, notice: 'Setup Your Lawfirm First'

    end
end
  end
  # GET /mycasecomments
  # GET /mycasecomments.json
  def index
    @mycasecomments = Mycasecomment.all
  end

  # GET /mycasecomments/1
  # GET /mycasecomments/1.json
  def show
	@mycasecomment = Mycasecomment.find(params[:id])
  end

  # GET /mycasecomments/new
  def new
  @mycase = Mycase.find(params[:mycase_id])
  @mycasecomment = @mycase.mycasecomments.build(mycasecomment_params)
  #@mycasecomment.user_id = current_user.id
  
  end

  # GET /mycasecomments/1/edit
  def edit
  end

  # POST /mycasecomments
  # POST /mycase comments.json
  def create
   @mycase = Mycase.find(params[:mycase_id])
  @mycasecomment = @mycase.mycasecomments.create(mycasecomment_params)
  @mycasecomment.mycasecommenter_id = current_user.id
   @mycasecomment.mycasecommenter_type = current_user.type
    @mycasecomment.save
  if @mycasecomment.save  
    if @mycase.users.any?
      @mycase.users.each do |f|
        CaseCommentEmailJob.set(wait: 20.seconds).perform_later(f, @mycase, @mycasecomment)
  
          Notification.create(
          notify_type: 'casecomment',
          actor: current_user,
          user: f,
          target: @mycase)
      end
    end


    Notification.create(
          notify_type: 'casecomment',
          actor: current_user,
          user: @mycase.admin,
          target: @mycase)

    Notification.create(
          notify_type: 'casecomment',
          actor: current_user,
          user: @mycase.client,
          target: @mycase) 

     CaseCommentEmailJob.set(wait: 20.seconds).perform_later(@mycase.admin, @mycase, @mycasecomment)
  
   CaseCommentEmailJob.set(wait: 20.seconds).perform_later(@mycase.client, @mycase, @mycasecomment)
  
    respond_to do |format|
      
        format.html { redirect_to meet_mycase_path(@mycase.id), notice: 'Dicussion posted was successfully created.' }
        format.json { render :show, status: :created, location: @mycasecomment }
		format.js
      end
    end
  end

  # PATCH/PUT /mycasecomments/1
  # PATCH/PUT /mycasecomments/1.json
  def update
    respond_to do |format|
      if @mycasecomment.update(mycasecomment_params)
        format.html { redirect_to meet_mycase_path(@mycase.id), notice: 'Mycasecomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @mycasecomment }
		format.js
      else
        format.html { render :edit }
        format.json { render json: @mycasecomment.errors, status: :unprocessable_entity }
		format.js
      end
    end
  end

  # DELETE /mycasecomments/1
  # DELETE /mycasecomments/1.json
  def destroy
     @mycase = Mycase.find(params[:mycase_id])
     @mycasecomment=@mycase.mycasecomments.find(params[:id])
	 @mycasecomment.destroy
    respond_to do |format|
      format.html { redirect_to meet_mycase_path(@mycase), notice: 'threat was successfully deleted.' }
      format.json { head :no_content }
	  format.js
    end
  end
  def download_file
  #@mycase = Mycase.find(params[:mycase_id])
  @mycasecomment=Mycasecomment.find(params[:id])
  send_file @mycasecomment.attachment.path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycasecomment
      @mycasecomment = Mycasecomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mycasecomment_params
      params.require(:mycasecomment).permit!
    end
end

app/helpers/mycasecomments_helper.rb
module MycasecommentsHelper
end

app/views/mycasecomments/_form.html.erb
<%= form_for([@mycase, @mycase.mycasecomments.build]) do |form| %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :mycasecomment_content, required="required" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Discussion", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/mycasecomments/_mycasecomment.html.erb
 <li>
                                         
 <div style="float:left; color:blue;">
 <span class="prfil-img"><%= image_tag mycasecomment.mycasecommenter.avatars_url, style:"width:50px;"%></span></div>

  <div style="float:right; color:blue;">
<%if mycasecomment%>    
   <h5><%= mycasecomment.mycasecommenter.full_name %></h5>
 <div class="box bg-light-info" style="float:right; color:orange;">

	<%= mycasecomment.content %> 
	</div></div>
	

    <%if mycasecomment.attachment?%>
	<%= link_to "get file", download_file_mycasecomment_path(mycasecomment), data: "case_file", class:'btn-info btn-xs' %>
	<br>
	<br>
    <%end%>
    <div class="chat-time" style="float:right; color:orange;"><%= time_ago_in_words(mycasecomment.created_at)%> ago
	<%= link_to "delete", [mycasecomment.mycase, mycasecomment], method: :delete, data: {confirm: "Are you sure"}%>
		
	 <%end%>
	</div>
        <div class="clearfix"> </div>
 </li>
	<br>


 

app/views/mycasecomments/edit.html.erb
<h1>Editing Mycasecomment</h1>

<%= render 'form', mycasecomment: @mycasecomment %>

<%= link_to 'Show', @mycasecomment %> |
<%= link_to 'Back', mycasecomments_path %>

app/views/mycasecomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mycasecomments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Mycase</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mycasecomments.each do |mycasecomment| %>
      <tr>
        <td><%= mycasecomment.content %></td>
        <td><%= mycasecomment.mycase_id %></td>
        <td><%= mycasecomment.user_id %></td>
        <td><%= link_to 'Show', mycasecomment %></td>
        <td><%= link_to 'Edit', edit_mycasecomment_path(mycasecomment) %></td>
        <td><%= link_to 'Destroy', mycasecomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mycasecomment', new_mycasecomment_path %>

app/views/mycasecomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @mycasecomment.content %>
</p>

<p>
  <strong>Content:</strong>
  <%= @mycasecomment.attachment_path %>
</p>

<p>
  <strong>Mycase:</strong>
  <%= @mycasecomment.mycase_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @mycasecomment.user_id %>
</p>

<%= link_to 'Edit', edit_mycasecomment_path(@mycasecomment) %> |
<%= link_to 'Back', mycasecomments_path %>